apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-ccm-k8s-auto
  labels:
    app: {{ .Values.app }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
      - name: harness-ccm-k8s-auto
        image: {{ .Values.image }}
        env:
        - name: HARNESS_ACCOUNT_ID
          value: {{ .Values.harness_account_id }}
        - name: HARNESS_PLATFORM_API_KEY
          value: {{ .Values.harness_platform_api_key }}
        # - name: LOOP_SECODS
        #   value: "number of seconds between checks (default: 60)"
        # - name: DELETE_CONNECTORS
        #   value: "if set (to anything) delete the connectors"
        # - name: ONESHOT
        #   value: "do not loop, execute once and quit"
        - name: LOG_LEVEL
          value: "debug"
